

CREATE TABLE EMP (
    ID NUMBER(7) PRIMARY KEY,
    LAST_NAME VARCHAR2(25) NOT NULL,
    FIRST_NAME VARCHAR2(25),
    DEPT_ID NUMBER(7),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPT(Dept_ID)
);



DESCRIBE EMP;



INSERT INTO EMP (ID, LAST_NAME, FIRST_NAME, DEPT_ID)
VALUES (101, 'Sam', 'Sundar', 10);


INSERT INTO EMP (ID, LAST_NAME, FIRST_NAME, DEPT_ID)
VALUES (101, 'Ram', 'Krishna', 20);


INSERT INTO EMP (ID, LAST_NAME, FIRST_NAME, DEPT_ID)
VALUES (102, 'Gopi', NULL, 40);


INSERT INTO EMP (ID, LAST_NAME, FIRST_NAME, DEPT_ID)
VALUES (103, NULL, 'Ram', 20);



COMMIT;